
name: ci

env: 
  IMAGE_ID: ghcr.io/smiggleworth/libpostal:python  

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build application image
      run: docker build -f ./src/Dockerfile -t $IMAGE_ID ./src

    - name: login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: push image
      run: docker image push $IMAGE_ID